export const CaseListMockData = [
    {
        caseNumber: 1234,
        bank: 'SBI',
        branch: 'HYD',
        inquiryId: 'CITIUS33',
        inquirerName: 'Citibank Limited New York swift',
        inquirerIdType: 'SWIFT',
        inquiryDate: '9/14/2020',
        inquirerAddress: 'CITIUS33 Swift, Citibank Limited New York swift',
        assignedTo: 'ISSACHI',
        status: 'Open',
        investigationType: 'TRACE',
        priority: 1,
        closeDate: '9/25/2020',
        amount: 1391.6,
        postDate: '9/2/2020',
        eqCurrency: 'AUD',
        currency: 'USD',
        tranRef: 'TRAN REF 123'
    },
    {
        caseNumber: 1330,
        bank: 'CNB',
        branch: 'BLR',
        inquiryId: 'CNBIN35',
        inquirerName: 'Canara Bank Bangalore',
        inquirerIdType: 'SWIFT',
        inquiryDate: '8/20/2020',
        inquirerAddress: 'CNBIN35 Swift, Canara Bank Bangalore',
        assignedTo: 'ISSACHI',
        status: 'Closed',
        investigationType: 'TRACE',
        priority: 2,
        closeDate: '8/20/2020',
        amount: 1391.6,
        postDate: '8/4/2020',
        eqCurrency: 'SGD',
        currency: 'USD',
        tranRef: 'TRAN REF 542'
    },
    {
        caseNumber: 2145,
        bank: 'PNB',
        branch: 'CNI',
        inquiryId: 'PNBIN66',
        inquirerName: 'Punjab National Bank Chennai',
        inquirerIdType: 'SWIFT',
        inquiryDate: '10/20/2020',
        inquirerAddress: 'PNBIN66 Swift, Punjab National Bank Chennai',
        assignedTo: 'ISSACHI',
        status: 'Closed',
        investigationType: 'TRACE',
        priority: 3,
        closeDate: '10/20/2020',
        amount: 1391.6,
        postDate: '8/4/2020',
        eqCurrency: 'SGD',
        currency: 'USD',
        tranRef: 'TRAN REF 665'
    },
    {
        caseNumber: 1485,
        bank: 'KMB',
        branch: 'DLI',
        inquiryId:  'KMBIN02',
        inquirerName: 'Kotak Mahindra Bank Delhi',
        inquirerIdType: 'SWIFT',
        inquiryDate: '4/20/2020',
        inquirerAddress: 'KMBIN02 Swift, Kotak Mahindra Bank Delhi',
        assignedTo: 'ISSACHI',
        status: 'Open',
        investigationType: 'TRACE',
        priority: 3,
        closeDate: '4/20/2020',
        amount: 1391.6,
        postDate: '2/4/2020',
        eqCurrency: 'SGD',
        currency: 'USD',
        tranRef: 'TRAN REF 148'
    }
];